const COURSE_ACTIONS = {
    SET_NEW_COURSE: 'SET_NEW_COURSE',
    ADD_MY_COURSES: 'ADD_MY_COURSES',
    GET_HOLE_INFO: 'GET_HOLE_INFO',
    SET_HOLE_INFO: 'SET_HOLE_INFO',
    ADD_COURSE: 'ADD_COURSE',
    CLEAR_COURSE_INFO: 'CLEAR_COURSE_INFO',
  };

export default COURSE_ACTIONS;